# Generated by Django 4.0.5 on 2022-07-06 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_pass', models.CharField(max_length=25)),
                ('phone', models.IntegerField()),
                ('dept', models.CharField(choices=[('I', 'IT'), ('H', 'HR')], max_length=10)),
                ('dob', models.DateField()),
                ('date_join', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('file', models.FileField(upload_to='file')),
                ('upload_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='fileDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_by', models.ManyToManyField(blank=True, related_name='personYes', to='fileApp.employee')),
                ('file_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileApp.file')),
                ('given_to', models.ManyToManyField(related_name='person', to='fileApp.employee')),
                ('rejected_by', models.ManyToManyField(blank=True, related_name='personNo', to='fileApp.employee')),
            ],
        ),
    ]
