# Generated by Django 4.0.5 on 2022-07-06 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='upload_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fileApp.employee'),
        ),
    ]
