# Generated by Django 4.0.5 on 2022-07-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileApp', '0003_alter_employee_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetail',
            name='given_to',
            field=models.ManyToManyField(blank=True, related_name='person', to='fileApp.employee'),
        ),
    ]
