# Generated by Django 4.0.5 on 2022-07-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileApp', '0004_alter_filedetail_given_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='img',
            field=models.ImageField(default='', upload_to='user'),
        ),
    ]
